In [2]:
import numpy as np


In [12]:
a = np.array([1,2,3])
print(a.ndim)

1


In [25]:
b = np.array([[1.1,2.4,3.3], [4.1,5.2,6.5]])
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)

[[1.1 2.4 3.3]
 [4.1 5.2 6.5]]
2
(2, 3)
float64


# Array indexing and slicing

In [29]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]], "\n")
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
print(c[1,2])
print("second,",c[1, :])
print("second to last row", c[-2, :])
print("last col", c[:, -1])

6
second, [4 5 6]
second to last row [4 5 6]
last col [3 6 9]


In [43]:
print("the middle two elements in row 2", c[1, 1:])
c[0,2] = 5
print(c)

the middle two elements in row 2 [5 6]
[[1 2 5]
 [4 5 6]
 [7 8 9]]


# Array operations

In [129]:
j = np.random.randint(10, size=(3,3))
print(j)
print(j.dtype)

[[2 5 1]
 [5 0 1]
 [8 6 8]]
int64


# Array effects

In [131]:
x1 = np.array([1,2,3])
x2 = np.array([4,5,6])
print(x1 + x2)
print(x1 * x2)



[5 7 9]
[ 4 10 18]
[[1 2 3]
 [4 5 6]]
[[100   2   3]
 [  4   5   6]]


In [132]:
y1 = np.array([[1,2,3], [4,5,6]])
y2 = y1.copy()
y2[0,0] = 100
print(y1)
print(y2)

[[1 2 3]
 [4 5 6]]
[[100   2   3]
 [  4   5   6]]


# Usefull numpy functions for data work

In [140]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr, '\n')
arr1 = np.repeat(arr, 2)
print(arr1, '\n')
arr2 = np.repeat(arr, 2, axis=0) #rows
print(arr2, '\n')
arr3 = np.repeat(arr, 2, axis=1) # cols
print(arr3, '\n')


[[1 2 3 4]
 [5 6 7 8]] 

[1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8] 

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]] 

[[1 1 2 2 3 3 4 4]
 [5 5 6 6 7 7 8 8]] 



# Usefull array operations

In [144]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print("vertical stacking:", np.vstack((a,b,a,b)))
print("horizontal stacking:", np.hstack((a,b,a,b)))


vertical stacking: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]
horizontal stacking: [ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]


# Usefull array operations

In [157]:
print("concatenate:", np.concatenate((a,b), axis=0)) # for rows
print("concatenate:", np.column_stack((a,b),)) # for columns
print("Vstack:", np.vstack((a,b)))


concatenate: [ 1  2  3  4  5  6  7  8  9 10]
concatenate: [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
Vstack: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Array Manipulation

In [159]:
x = np.arange(1, 10, 2)
print(x)
x = np.linspace(1, 10, 5)
print(x)

[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [175]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr.reshape(1,9))
print("transpose:", arr.T)
print("flatten," , arr.flatten())

[[1 2 3 4 5 6 7 8 9]]
transpose: [[1 4 7]
 [2 5 8]
 [3 6 9]]
flatten, [1 2 3 4 5 6 7 8 9]


# Append Array to Another

In [14]:
u = np.array([[1,2,3,4], [5,6,7,8]])
u1 = np.append(u, [[9,10,11,12]], axis=0)
print(u1, "\n")
u2 = np.append(u, [[9],[10]], axis=1)
print(u2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] u1:

[[ 1  2  3  4  9]
 [ 5  6  7  8 10]]


# Insert And Delete from Array

In [29]:
r = np.array([[1,2,3,4], [5,6,7,8]])
r1 = np.insert(r,1, [[9,10,11,12]], axis=0)
print(r1, "\n")
r2 = np.insert(r, 4, [9,10], axis=1)
print(r2, "\n")
r_c = np.copy(r)
r3 = np.delete(r_c, 1, axis=0)
print(r3)

[[ 1  2  3  4]
 [ 9 10 11 12]
 [ 5  6  7  8]] 

[[ 1  2  3  4  9]
 [ 5  6  7  8 10]] 

[[1 2 3 4]]


# Select Array Subset

In [33]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, "\n")
print(a[1:3, 1:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 6  7  8]
 [10 11 12]]


# Array Operations

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject